# Hlavní konfigurační soubor pro testování baterie

[general]
# Cesta k sériovému portu DUT (např. /dev/ttyACM0 nebo COM3)
dut_serial_port = "/dev/ttyACM0"
# Adresář pro ukládání výsledných CSV souborů
output_directory = "test_results"
# Interval logování dat v sekundách
log_interval_seconds = 1
# Povolit simulaci DUT? true = simulace, false = reálné DUT
simulate_dut = true

[relay]
# IP adresa Deditec relé desky
ip_address = "192.168.1.10" # <-- ZMĚŇ NA SKUTEČNOU IP!

# Seznam čísel relé (1-16), které spínají USB +5V VBUS
# I když je jen jedno, definujeme jako seznam pro konzistenci
usb_power_relay_pins = [1, 4, 6]

# Seznam čísel relé (1-16), které spínají HW enable nabíječky (volitelné)
# Pokud nepoužíváš, můžeš dát prázdný seznam: charger_enable_relay_pins = []
charger_enable_relay_pins = [2]

# Seznam čísel relé (1-16) připojených k bzučáku (volitelné)
# Může být více bzučáků nebo jen jeden
beeper_pins = [8]

# --- NOVÁ SEKCE (Příklad pro budoucí použití) ---
# Můžeš si definovat skupiny pinů pro specifické účely
# Například pro spínání různých zátěží v testu
# load_relay_pins_group1 = [9, 10]
# load_relay_pins_group2 = [11]
# ---------------------------------------------

[temperature_chamber]
# Povolit automatické ovládání komory? false = manuální režim s čekáním na Enter
enabled = false
# Timeout [s] pro čekání na stabilizaci teploty (použito jen pokud enabled = true)
stabilization_timeout_seconds = 1800
# Zde přidej specifická nastavení pro tvou komoru, pokud enabled = true
# např. connection_string = "GPIB0::1::INSTR"

[test_plan]
# Teploty [°C], při kterých se mají testy provést
temperatures_celsius = [25, 0, -20, 50] # Příklad
# Které testovací módy se mají spustit pro každou teplotu a cyklus?
# Možnosti: "linear", "switching", "random"
test_modes = ["linear", "switching"] # Spustí Linear a pak Switching
# Počet kompletních cyklů (všech zvolených módů) pro každou teplotu
cycles_per_temperature = 1

# --- Parametry pro Linear Test ---
linear_discharge_voltage_limit = 3.0       # Cílové napětí [V] pro konec vybíjení
linear_charge_idle_current_threshold_ma = 50 # Prah proudu [mA] pro konec nabíjení

# --- Parametry pro Switching Test ---
# Simuluje rychlé změny - např. střídání nabíjení/vybíjení nebo enable/disable
switching_phase_duration_s = 30    # Jak dlouho trvá jedna fáze (např. 5 minut nabíjení, 5 minut vybíjení, 5min = 5 * 60)
switching_interval_s = 10              # Jak často přepínat stav (v sekundách)
switching_charge_command = "enable_charging" # Příkaz pro "zapnutí" v cyklu
switching_discharge_command = "disable_charging" # Příkaz pro "vypnutí" v cyklu (nebo jiný pro aktivní vybíjení?)

# --- Parametry pro Random Wonder Test ---
random_duration_s = 30             # Celková délka Random testu (např. 30 minut = 30 * 60)
random_min_phase_s = 15                # Minimální doba trvání jedné fáze (nab/vyb)
random_max_phase_s = 30               # Maximální doba trvání jedné fáze
random_charge_probability = 0.6        # Pravděpodobnost, že další fáze bude nabíjení (0 až 1)

# Bezpečnostní limity pro Random test (NUTNO PEČLIVĚ NASTAVIT!)
random_max_voltage = 4.25              # Horní hranice napětí
random_min_voltage = 2.9               # Dolní hranice napětí
# Pokud DUT podporuje nastavení proudu, přidat:
# random_max_charge_current_ma = 600
# random_min_charge_current_ma = 50
# random_max_discharge_current_ma = -400 # Záporný!
# random_min_discharge_current_ma = -100 # Záporný!

# --- Společné parametry ---
# Délka relaxačních pauz [s] (může být specifická pro mód?)
relaxation_time_seconds = 10 # Krátká pro testování

# --- NOVÁ SEKCE: Notifications ---
[notifications]
# Metoda upozornění pro manuální krok teploty: "beeper", "slack", "both", "none"
manual_temp_mode = "slack"

# Nastavení pro Slack (vyplň, pokud používáš "slack" nebo "both")
# URL Webhooku ze Slack aplikace (!!! NEUKLÁDEJ DO VEŘEJNÉHO GITU !!!)
slack_webhook_url = "https://hooks.slack.com/services/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"


[dut_commands]
# !!! UPRAV PODLE SVÉHO DUT !!!
# Příkazy posílané do DUT přes sériový port (prodtest_cli)

# Základní ovládání a čtení
enable_charging = "charger enable"
disable_charging = "charger disable"
get_voltage = "battery voltage?"
get_current = "battery current?"
get_status = "system status?" # Očekává se odpověď obsahující CHARGING/DISCHARGING/IDLE

# Příkazy pro další data (podle formátu)
get_dut_time = "system time?"           # Očekává čas v ms
get_ntc_temp = "temp ntc?"              # Očekává teplotu NTC v °C
get_vsys = "system vsys?"               # Očekává napětí Vsys v V
get_die_temp = "temp chip?"             # Očekává teplotu čipu v °C
get_iba_meas_status = "charger ibastat?" # Očekává stav měření proudu
get_buck_status = "charger buckstat?"    # Očekává stav buck
# Volitelně: set_charge_current = "charger current {current_ma}"
# Volitelně: set_discharge_load = "battery load {load_ma}" # Pro aktivní vybíjení?
